name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Lint
        run: flake8 src/ tests/ --max-line-length=120 --ignore=E501,W503

      - name: Run tests
        run: pytest -v --tb=short

      - name: Build check
        run: |
          pip install build twine
          python -m build
          python -m twine check dist/* || true
